---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: demo-rolling-updater
  labels:
    app: demo
spec:
  replicas: 2
  strategy: # ramped doesn’t require any extra step (kubectl apply is enough)
    type: RollingUpdate    
    rollingUpdate:      
       maxSurge: 50%  # how many pods we can add at a time      
       maxUnavailable: 0  
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: nginx:stable
        name: nginx-demo
        imagePullPolicy: Always
        ports:
        - name: http 
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "256m"          
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html # Ojo, este es el nombre del archivo que está en el configmap  -->  index.html: |-
          readOnly: true
      volumes:
        - name: index-html
          configMap:
            name: configmap-index-html
            
---            
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-demo
  namespace: demo-rolling-updater
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#       averageUtilization: 60
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60

