---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-rolling-updater
  name: service-demo-nginx
  annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /metrics
        prometheus.io/port:   '9100'
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=dev,owner=SRE,job=demo"
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb # Es el unico que soporta hasta el momento (si no pongo nada, usa el classic)
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "3"
        service.kubernetes.io/local-svc-only-bind-node-with-pod: "true"
  labels:
    app: demo
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP    
  selector:
    app: demo

